version: '3'
services:
  web:
    build: .
    command: bash -c "yarn && yarn dev"
    ports:
      - "80"
    volumes:
      - .:/usr/app/
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    build: ./Docker/Database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: not
      POSTGRES_DB: nodeTest
    networks:
      - backend
networks:
  backend: